database:
  host: ""
  port: ""
  user: ""
  password: ""
  database_name: ""
listener_toggle:
  xpbottlebreaklistener: true
  shearsheeplistener: true
  joinleavelistener: true
  cheatsinterface: true #listener + command
  chatcolorlistener: true
  dblisteners: true
command_toggle:
  gmc: true
  gms: true
  gma: true
  gsp: true
  die: true
  heal: true
  fly: true
  invulnerable: true
  message: true
  smsg: true
  enderchest: true
  togglepvp: true